### ISSUE TITLE
Please Create An Example that uses MongoDB

### ISSUE THREAD

**Issue by pmustoe30** [NEventStore/Obsolete-NEventStore-Example#2]
I'm having problems finding good documentation around integrating / setting up NEventStore with Mongo.  Am I missing some obvious resources on the net?  Mr. Google is coming back with lots of nothing from what I can tell.  

It would be wonderful to have an example of using NEventStore with MongoDB.

You'd kill two birds with one stone.  A) You won't have to write prose documentation on this.  B) those integrating your project with Mongo have a starting point to work from / guide them.

**Comment by AGiorgetti** [comment]
cleanup old issues
