### ISSUE TITLE
The repository is not updated for a while- please remove it

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [NEventStore/Obsolete-NEventStore-Example#3]
The repository is not updated for a while and not compilable anymore.
The examples inside NEventStore:  https://github.com/NEventStore/NEventStore/tree/master/src/NEventStore.Example and 
https://github.com/NEventStore/NEventStore/tree/master/src/NEventStore.PollingClientExample are working fine and should be used for quick start.
Please remove the repository to avoid confusion.

**Comment by AGiorgetti** [comment]
Marked as obsolete, I'll remove this project at a later time, in the meanwhile I might use it to test nuget packages.
